export const GET_INCIDENTS_REQUESTED = "GET_INCIDENTS_REQUESTED";
export const GET_INCIDENTS_SUCCESS = "GET_INCIDENTS_SUCCESS";
export const GET_INCIDENTS_FAILED = "GET_INCIDENTS_FAILED";

export const POST_INCIDENT_REQUESTED = "POST_INCIDENT_REQUESTED";
export const POST_INCIDENT_SUCCESS = "POST_INCIDENT_SUCCESS";
export const POST_INCIDENT_FAILED = "POST_INCIDENT_FAILED";

export const PUT_INCIDENT_REQUESTED = "PUT_INCIDENT_REQUESTED";
export const PUT_INCIDENT_SUCCESS = "PUT_INCIDENT_SUCCESS";
export const PUT_INCIDENT_FAILED = "PUT_INCIDENT_FAILED";

export const DELETE_INCIDENT_REQUESTED = "DELETE_INCIDENT_REQUESTED";
export const DELETE_INCIDENT_SUCCESS = "DELETE_INCIDENT_SUCCESS";
export const DELETE_INCIDENT_FAILED = "DELETE_INCIDENT_FAILED";

export const TOOGLE_MODAL_FORM = "TOOGLE_MODAL_FORM";
export const CLEAR_CODE = "CLEAR_CODE";

export const FILTER_SEARCH = "FILTER_SEARCH";
export const FILTER_DATE = "FILTER_DATE";
export const FILTER_STATUS = "FILTER_STATUS";
